### PR TITLE
Added Background music

### PR DESCRIPTION
**Pull request by abhishekrawe**
Added background music that changes dynamically according to the weather condition currently the background music is playing via onclick functionalities and  I am working on finding the solution to autoplay the music.

### CODE REVIEW

**Comment by yashika51** [comment]
@abhishekrawe status on this? Have you added the changes regarding icon that we discussed yesterday?

**Comment by abhishekrawe** [comment]
Yes @yashika51 it's done ✅

**Comment by abhishekrawe** [comment]
Please review this issue @yashika51

**Comment by abhishekrawe** [comment]
It is Ready to Merge @yashika51, please merge it.

**Comment by Mayank17M** [comment]
@abhishekrawe I think you have some prettier errors that's why the build is failing. I can help you resolve them if you want.

**Comment by yashika51** [comment]
We need to fix the errors and conflict first @abhishekrawe

**Comment by yashika51** [comment]
@abhishekrawe status?

**Comment by abhishekrawe** [comment]
Resolved conflicts, @yashika51, ready to merge

**Review by Mayank17M — APPROVED** [review]
LGTM! 🥳
It would be better if you can move the audio files to the assets folder we already have. 
And change the imports from `./assets/morningbird.mp3` to `../../assets/morningbird.mp3` and similarly for others.

**Comment by yashika51** [comment]
@abhishekrawe yeah I would suggest keeping audio files in assets

**Comment by Mayank17M** [comment]
@yashika51 this is ready for merge.

**Pull request merged**
