### PR TITLE
Made weather card component and changed styling

### PR DESCRIPTION
**Pull request by PAOK-2001**
# Changes made
-  Moved weather card from App.js to dedicated component to clean up code.
-  Changed styling of search bar to better fit the design language of the page.

# Preview
CardSearch

### CODE REVIEW

**Comment by PAOK-2001** [comment]
@suraj-singh127  @yashika51 please review.

**Review by suraj-singh127 — APPROVED** [review]

**Comment by suraj-singh127** [comment]
Looks great!

**Review by n00bmaster2810 — APPROVED** [review]
Looks perfect.

**Comment by shamvi-05** [comment]
The UI is really looking amazing!!

**Review by shamvi-05 — APPROVED** [review]
The UI looks really amazing!

**Pull request merged**
