### PR TITLE
integrated newsAPI with frontend

### PR DESCRIPTION
**Pull request by AnushaNathRoy**
integrated NewsAPI with frontend. The PR is still in the works.

### CODE REVIEW

**Comment by n00bmaster2810** [comment]
@AnushaNathRoy you should first fetch upstream to your main and then pull from there. Then try to merge your changes with the main branch locally so as to resolve these conflicts.

**Comment by shamvi-05** [comment]
> @AnushaNathRoy you should first fetch upstream to your main and then pull from there. Then try to merge your changes with the main branch locally so as to resolve these conflicts.

Yeah Once we are done with the work we will fetch the upstream and make a new PR! Thanks for the info.

**Comment by yashika51** [comment]
@shamvi-05 no need to create a new PR you can resolve conflicts in this one itself.

**Comment by AnushaNathRoy** [comment]
The PR is still a work in progress. In this commit:

-  There have been changes made to the UI to make the cards look better
- A read more button and toggle expansion have been created
- A share button that copies the URL of the news to the clipboard

image
image

Changes left to make:

- Integrate the whole News section with the rest of the website
- Make the `For You` and `The World` sections more distinguishable in UI. 
- Dynamically get the `For You` data from the user's current location.

**Pull request closed without merging**
