### PR TITLE
Geolocation integrated

### LINKED ISSUE #3: Using Geolocation API to get the users location
Using the Geolocation API to get the users location as the first weather results displayed, instead of just New York City.

Read more [here](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API).

### PR DESCRIPTION
**Pull request by suraj-singh127**
Fixed the Merge conflicts occurring caused due to merging #36 and #34

After the final changes the Weather App looks good and flawless.

image
 
Awesome work done by @ankitaugale23 and @JyotimoyKashyap on the solving the Geolocation problem
Closes #3

### CODE REVIEW

**Comment by suraj-singh127** [comment]
@PAOK-2001, @ankitaugale23 @JyotimoyKashshyap @yashika51 please review.

**Comment by PAOK-2001** [comment]
Looks good! It integrates all the changes thus far. Should get merged to work untop a stable version.

Nice work everyone.

**Review by PAOK-2001 — APPROVED** [review]
Great job

**Comment by ankitaugale23** [comment]
Looks great. Great work for solving the merge conflicts.

**Pull request merged**
