### PR TITLE
Adding loader music recommendations

### LINKED ISSUE #58: Music Recommender enhances and edge cases
Work on a few edge cases and enhancements for the music recommender

- [x] Work on the initialization issue and bad API calls
- [ ] Automatically stop music playing for an already running audio card when another audio card starts playings
- [ ] Add a loader for when changing the layouts
- [ ] Put a loader in place for song cards(or hide it) when the weather API is loading
- [ ] Show more button/Pagination to allow more songs to show up, currently the limit is 6
- [ ] UI enhancements where possible - Particularly for the preference cards

### PR DESCRIPTION
**Pull request by OmkarAcharekar**
Fixes #58 Task  3 & 4

Display the loader in  place for song cards  when the weather API is loading

### CODE REVIEW

**Comment by OmkarAcharekar** [comment]
@Mutugiii @yashika51  can you please review this?

**Comment by yashika51** [comment]
@OmkarAcharekar conflicts ^

**Comment by OmkarAcharekar** [comment]
@yashika51  can you review this?

**Comment by OmkarAcharekar** [comment]
@yashika51  It can be merged now. I have made the  changes

**Comment by yashika51** [comment]
Conflicts @OmkarAcharekar ^

**Comment by OmkarAcharekar** [comment]
@yashika51 I have fixed merge conflicts

**Pull request merged**
