### PR TITLE
Navbar added

### PR DESCRIPTION
**Pull request by suraj-singh127**
image

Added a Navigation bar to traverse the page.

@yashika51 and @PAOK-2001 please review the changes

### CODE REVIEW

**Review by yashika51 — CHANGES_REQUESTED** [review]
We should add a `.gitignore` file ignoring environment files and cache files. I gave the same suggestion here https://github.com/MLH-Fellowship/prep-project-22.P3.1/pull/27#pullrequestreview-942886712

Adding it to either of the PR would solve the purpose.

**Comment by suraj-singh127** [comment]
.eslint file keeps generating everytime we run the project locally. This issue is still open https://github.com/facebook/create-react-app/issues/10306 and has not been resolved yet.

A fix is deleting the .eslintcache file before commiting the changes pushing them upstream.

**Comment by PAOK-2001** [comment]
The nav bar looks great! And I see you have integrate some of the changes I made to avoid conflicts on merge! Great job!

**Review by PAOK-2001 — APPROVED** [review]

**Comment by suraj-singh127** [comment]
After final changes - 

screenshot (7)

This PR closes issues #2  #13

**Review by Mayank17M — CHANGES_REQUESTED** [review]
This looks great!
The images can be moved to a different folder. Something like `./assets/images/cloud.jpeg`. Also, there should be a separate component for `backgroundArray`

**Comment by suraj-singh127** [comment]
I moved the images to a backgroundArray component and changed the imports 
@Mayank17M @PAOK-2001 @yashika51 can you please review.

**Review by PAOK-2001 — APPROVED** [review]
Looks ready to merge! Good job. The changes Mayank help give better structure to the proyect

**Pull request merged**
