### PR TITLE
[Feature] Toggle for getting back to user's default location. 

### LINKED ISSUE #60: [Feature] Toggle to return to user's location
#### Problem: 
In the current state of the website, the user's location is fetched at the start, but if the user starts exploring different cities then there's is no option to return to their original location. 

#### Solution: 
The solution to this problem is to add a toggle or icon to the right side of the search city field, that would allow the user to return to their location.

### PR DESCRIPTION
**Pull request by JyotimoyKashyap**
Fixes #60 

Explanation : 
On clicking the button it takes the user back to its current location. 

Screenshot of the UI: 
react

### CODE REVIEW

**Comment by yashika51** [comment]
@JyotimoyKashyap conflicts ^

**Comment by JyotimoyKashyap** [comment]
> @JyotimoyKashyap conflicts ^

Will verify and comment if its safe to merge this pull request once tested.

**Comment by yashika51** [comment]
Good approach 👍

**Review by JyotimoyKashyap — COMMENTED** [review]
Looks good to me

**Review by JyotimoyKashyap — COMMENTED** [review]
This PR can be merged now

**Comment by yashika51** [comment]
Final conflicts to resolve @JyotimoyKashyap

**Comment by JyotimoyKashyap** [comment]
@yashika51 this PR is ready to be merged.

**Pull request merged**
