### PR TITLE
Temperature Conversion Toggle Feature

### PR DESCRIPTION
**Pull request by ankitaugale23**
[X] User can toggle between celsius and Farheniete using the toggle switch 
Solves the issue #43

### CODE REVIEW

**Comment by ankitaugale23** [comment]
temp ss
This is how it looks styling wise, any other changes I can make in styling? @yashika51 @PAOK-2001

**Comment by yashika51** [comment]
@ankitaugale23 maybe just decrease the size of the button a bit

**Comment by ankitaugale23** [comment]
> @ankitaugale23 maybe just decrease the size of the button a bit

sure, will do that

**Comment by ankitaugale23** [comment]
mlh temp ss
Is this okay or should I reduce it further?

**Review by yashika51 — APPROVED** [review]

**Comment by yashika51** [comment]
LGTM!

**Pull request merged**
